# Use image that already had Lando installed.
image: devwithlando/gitpod:1

tasks:
  - name:  Setup Drupal for Lando.
    command: |
      lando init --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components 1" --recipe drupal10 --webroot . --name drupal_starter
      lando start
      lando composer require drush/drush
      lando composer install -n
      chmod ug+w -R /workspace/gitpod/sites/default/
      lando drush si -y --account-pass=admin --site-name='lando_drupal10' --db-url=mysql://drupal10:drupal10@database/drupal10
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))

ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 9003
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language